id: qbittorrent
name: qBittorrent
description: Lightweight BitTorrent client with a powerful WebUI. Fast, stable, and runs natively on Alpine Linux.
overview: |
  qBittorrent is a free, open-source BitTorrent client with a clean web interface that rivals the
  best desktop clients. It runs headless as qbittorrent-nox, making it perfect for LXC containers.

  Features include RSS feed support, sequential downloading, bandwidth scheduling, IP filtering,
  and a full Web API for integration with tools like Sonarr, Radarr, and Prowlarr.

  This container runs on Alpine Linux for minimal resource usage. After installation, access the
  WebUI to configure your download settings. The default login is admin with the password shown
  in the install outputs.
version: "5.1.0"
categories:
  - media
  - tools
tags:
  - torrent
  - bittorrent
  - download
homepage: https://www.qbittorrent.org
license: GPL-2.0
maintainers:
  - PVE App Store

official: true
lxc:
  ostemplate: alpine-3.22
  defaults:
    unprivileged: true
    cores: 2
    memory_mb: 2048
    disk_gb: 4
    features:
      - nesting
    onboot: true

volumes:
  - name: downloads
    type: bind
    mount_path: /downloads
    label: Downloads
    default_host_path: /mnt/storage/downloads
    required: false
    description: Download destination directory

inputs:
  - key: webui_port
    label: WebUI Port
    type: number
    default: 8080
    required: false
    group: Network
    description: Port for the qBittorrent web interface.
    help: Default 8080; must be between 1024-65535
    validation:
      min: 1024
      max: 65535
  - key: torrent_port
    label: Torrent Port
    type: number
    default: 6881
    required: false
    group: Network
    description: Port for incoming BitTorrent peer connections.
    help: Forward this port on your router for best performance
    validation:
      min: 1024
      max: 65535
  - key: download_path
    label: Download Directory
    type: string
    default: /downloads
    required: false
    group: Storage
    description: Default download directory for completed torrents.
    help: Must be an absolute path
  - key: initial_password
    label: Initial WebUI Password
    type: secret
    default: changeme
    required: false
    group: General
    description: Initial password for the admin user. Change this after first login.
    help: Username is always 'admin'

permissions:
  packages:
    - qbittorrent-nox
    - python3
    - p7zip
  paths:
    - "/etc/init.d/"
    - "/var/lib/qbittorrent/"
    - "/downloads/"
    - "/etc/apk/"
    - "/etc/conf.d/"
  services:
    - qbittorrent-nox
  users:
    - qbittorrent
  commands:
    - sed

provisioning:
  script: provision/install.py
  timeout_sec: 300

outputs:
  - key: webui_url
    label: WebUI
    value: "http://{{ip}}:{{webui_port}}"
  - key: webui_user
    label: Username
    value: admin
  - key: torrent_port
    label: Torrent Port
    value: "{{torrent_port}}"

gpu:
  supported: []
  required: false
